#pragma once
#include <memory>
#include <iostream>
#include <chrono>
#include <vector>
#include <array>
#include <random>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>